MANIFEST.in

Installing the package from source tarball fails as the setup.py tries to open two files that are not part of the tarball.
With a MANIFEST.in to include README.md and requirements.txt as needed by
setup.py, everything is well.
Before this fix:
```
arnold@xingu:~/programme$ pip install dist/aiohue-1.3.0.tar.gz
Processing ./dist/aiohue-1.3.0.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-fop5pmr6/aiohue/setup.py", line 4, in <module>
long_description = open('README.md').read()
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fop5pmr6/aiohue/
You are …
```

Fix pip install from source by adding MANIFEST.in

---

aiohue/lights.py

As documented in https://developers.meethue.com/documentation/lights-api#14_get_light_attributes_and_state

Add 'productname' and 'modelid' to Light

---

aiohue/lights.py
requirements.txt

This Pull Request is needed for the "Improve Philips Hue color conversion" PR in HomeAssistant:
https://github.com/home-assistant/home-assistant/pull/19123
This adds the capability to get and parse the color gamut information that is supplied by the Hue bridge.
Tested this PR with HomeAssistant and everthing works just fine.

add get gamut information

---

aiohue/sensors.py
example.py
setup.py

* Add `ZLLRelativeRotary` sensor as a new `ZLLSensor` with `rotaryevent` property instead of `buttonevent`. Correspondence with model id "Z3-1BRL", (Lutron Aurora Rotary)
* Bump minor version to 2.0.1

Add support for ZLLRelativeRotary sensor

---

MANIFEST.in

It is needed for Fedora packaging.

Include LICENSE in the manifest

---

aiohue/bridge.py

It seems like Hue is going to be HTTPS only in their latest firmware update.
All documentation already writes solely about `https` communications. This PR adjusts the behavior of `aiohttp` to work with that.
By default we are going to assume `https` and try a small head request to the hub. If that fails, we are going to assume `http`. This is mainly in place to keep backward compatibility (assumingly with the oldest of Hue hubs).
Related to home-assistant/core#50110

Fix Hue communication protocol

---

aiohue/__init__.py
aiohue/api.py
aiohue/bridge.py
aiohue/clip.py
aiohue/groups.py
aiohue/lights.py
aiohue/scenes.py
aiohue/sensors.py
example.py

This will give an instant state update instead of having to poll.
This is MVP with some basic info for a light.
Test it out with `python3 example.py`. To see debug logs, run `DEBUG=1 python3 example.py`
Thanks to a discovery by @Thomas-Vos

Allow listening for Hue events

---

README.md
aiohue/clip.py
example.py

Hue hubs disconnect our event connection at second 24, next time at 54, ~6 minutes after connecting. So set timeout to 6 minutes.
Also logging the device states in the example so we can easier map it.
```
21:34:54 Event endpoint disconnected
21:34:54 Subscribing to events
21:41:24 Event endpoint disconnected
21:41:24 Subscribing to events
21:47:54 Event endpoint disconnected
21:47:54 Subscribing to events
21:54:24 Event endpoint disconnected
21:54:24 Subscribing to events
22:00:54 Event endpoint disconnected
22:00:54 Subscribing to events
22:07:24 Event endpoint disconnected
22:07:24 Subscribing to events
22:13:54 Event endpoint disconnected
22:13:54 Subscribing to events
22:20:24 Event endpoint disconnected
22:20:24 Subscribing to events
22:26:54 Event endpoint disconnected
22:26:54 …
```

Set timeout

---

aiohue/sensors.py
example.py

This is a workaround for #63, it ignores non button events on switches.
Of course, the better approach would be to properly handle `device_power` events and update the state of the sensor.
My understanding of the API is that consumers have to compare before and after state in order to compute what changed.
That makes a lot of sense for lights, where you can then track if the light was switched or dimmed.
However, for switches we may want to be able to distinguish between button presses (which could be two consecutive events with the same button id), and other events which could be a change in battery level.
What's your opinion on this? Should we introduce a `button_event` flag that would be True only when the event was a button press?

Ignore non-button events on switches

---

aiohue/sensors.py

Temperature events come in with "normal" values while the fetched state is * 100. 
CC @jbouwh can you help test this?

Fix temperature event

---

aiohue/bridge.py

Guard for `id_v1` that have no `/`
```
2021-10-04 21:05:57 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/home/paulus/dev/hass/core/homeassistant/components/hue/bridge.py", line 249, in _subscribe_events
async for updated_object in self.api.listen_events():
File "/home/paulus/dev/hass/core/venv/lib/python3.9/site-packages/aiohue/bridge.py", line 212, in listen_events
item_type = event_data["id_v1"].split("/", 2)[1]
IndexError: list index out of range
```

Guard for unexpected ID v1

---

aiohue/util.py
aiohue/v2/controllers/config.py

The network mac address is no longer provided in the api.
The current code returns the zigbee mac address of the bridge which is incorrect.
As the bridge_id is created from the network mac address, added a small helper to parse the network mac from the bridge id.

Parse correct mac address

---

aiohue/v2/models/feature.py

Looks like the mirek min/max values are not reported correctly for (some?) third party bulbs.
This workaround that by auto correcting the wrong values.
fixes https://github.com/home-assistant/core/issues/61584

Add workaround for lights providing incorrect capabilities

---

aiohue/v2/controllers/lights.py

Add ability to set the alert feature in an attempt to bring back the flash effect.
Related to https://github.com/home-assistant/core/issues/61560#issuecomment-991946211

Add alert feature

---

aiohue/util.py
aiohue/v2/controllers/lights.py

Minor fix in the parser that converts the raw data into the dataclasses from model.
When the parser is unable to parse an incoming value it will raise an exception.
If the value is however defined as optional in the model, it will now log the error only and treat the value as None.
fixes https://github.com/home-assistant/core/issues/61529
Although the xy value should be required in the "colorfeature" object according to the documentation, we've got a report where it wasn't. Third party bulb not behaving according to specs maybe ?
Anyways, this will workaround that without breaking anything downstream.

Add fallback for unparseable value that is optional

---

aiohue/v2/controllers/lights.py

Remove check for valid transition time as it is already checked by the bridge itself.
If you send a value that is out of range, the bridge will throw an error.
In fact you can actually send value 0 to turn off the transition time.
fixes https://github.com/home-assistant/core/issues/61631

Remove check for valid transition time

---

aiohue/v2/models/button.py
docs/clip-api.schema.json

I was looking around the code for the first time and noticed this class name that looks like a typo: "ButtOnFeature" instead of "ButtonFeature".

Fix typo in class name

---

aiohue/v2/__init__.py
aiohue/v2/controllers/events.py
requirements.txt

- Prevent deadlocking of SSE connection with timeout on connection and receiving of events
- Use timeout 0 on aiohttp request itself to prevent it from disconnecting the stream
- Send full state events when the connection is reconnected
- Use connection:close on SSE endpoint to prevent 503 server error
Tested this very well under different conditions and this time it holds up.
Deadlock timeout is 60 minutes, meaning that if there's not a single event received within an hour, the connection will be recreated.
This fixes https://github.com/home-assistant/core/issues/61926
yeah, this time for real ;-)

Fix connection logic with timeout guard

---

aiohue/v2/__init__.py
aiohue/v2/controllers/base.py
aiohue/v2/controllers/events.py
requirements.txt

- Emit events with connection state so consumers can act on it
- refresh state in controllers based on connection event
- Use aiohttp socket read timeout to detect stopped stream
- Guard 503 errors

Change reconnect logic (again)

---

aiohue/v2/controllers/events.py
aiohue/v2/models/geofence_client.py

Get ready for some real funky stuff here...
This adds support for a keepalive by abusing the geofence_client resource to set a unique name every interval, which in turn results in an event on the eventstream. 
As far as I can see this causes no side effects but we might want to feature-toggle it with an environmental variable or something (if we even consider adding this).

Add Keep alive workaround

---

aiohue/v2/__init__.py
aiohue/v2/controllers/base.py
aiohue/v2/controllers/events.py

Turns out that Last-Event-ID does actually work on the V2 API. Key was not stripping of the colons.
This change will make sure to just rely on the SSE "last-event-id" logic so any missed events will be received at reconnect.
If the reconnect took more than 1 minute, we fallback to a full state fetch just to be safe.
Button events are filtered out when a new state is retrieved, to fix the issue with "ghost events" for Hue Tap remotes reported by people when a reconnect was happening.

Fix reconnect last event id

---

aiohue/v2/controllers/sensors.py

Initializing it on class level means it's shared across instances. Better to initialize it when needed on a per-instance basis.
Since item IDs are random, probably not an issue. Just cleaner.

Delay initializing workaround dict

---

aiohue/v2/__init__.py
requirements.txt
setup.py

According to Signify support it is very important that we have a guard in place to make sure that there are no more than 3 concurrent requests to the bridge. Putting this guard on the TCP Connector for aiohttp solves all 503 errors.
Sending 100 requests now completes in 2,2 seconds without a single 503 error ;-)
I've put a small detection in the code if a TCP connector is given without this limit (e.g. Home Assistant as a temporary measure until we can adjust the global logic in HA to respect this host limit.

Switch to limit per host on tcp connector

---

requirements.txt

We removed `asyncio-throttle` from requirements in #104 but it was still in use for v1 API.

Put back asyncio-throttle

---

aiohue/v2/controllers/base.py

- Adjust the reconnect logic to the recent model changes.
- Prevent state update events emitted to subscribers when nothing changed.
- Try to prevent false positive button events when the bridge is restarting or updating or the connection reestablished.
This (partially) fixes https://github.com/home-assistant/core/issues/65122

Small follow up fix in event logic

---

aiohue/util.py
tests/v2/test_parser.py

Another edgecase in parsing the json into our (dataclass) models.
If a float value is exactly one, it is sent as 1 (int) in the API, causing a schema mismatch.
Added a small fix for this situation by allowing an int value to be converted to float.
Also added some basic tests for the parser logic.
Fixes #116

Fix float int conversion

---

aiohue/v2/controllers/base.py
aiohue/v2/controllers/config.py
aiohue/v2/controllers/groups.py
aiohue/v2/controllers/scenes.py
aiohue/v2/controllers/sensors.py

In an attempt to not completely crash when a single resource can't be parsed due to API schema mismatches, bugs in Hue or other factors, we allow some resources to be skipped. 
This only works for resources that are not dependees for other resources so we define this in the controller level.

Loosen up a bit on parser errors

---

aiohue/v2/controllers/groups.py
aiohue/v2/models/room.py

While fixing all API schemas to the ones reported in the (now released) API docs I missed a small spot according to how lights are grouped within a zone/room impacting the way how to retrieve lights within a room/zone. While the old way still works in non-beta Hue firmwares, getting the lights for a room needs to be done by looking at the devices in the group.
Changed the logic a bit so we can retrieve the lights for a zone/room which works on current Hue firmware (1.49) and beta firmware (1.50).
Signify is preparing a change to the rooms/zones/grouped_light schemas, allowing us to send light commands to a grouped_light directly instead of sending each command to all individual lights.
Great news as this was a feature request we did ourselves.
I've not yet implemented this change because …

Fix changes in group (room/zone) models

---

aiohue/errors.py
aiohue/v2/controllers/config.py
aiohue/v2/controllers/groups.py
aiohue/v2/models/feature.py
aiohue/v2/models/grouped_light.py
aiohue/v2/models/light.py
requirements.txt
tests/v2/test_init.py

No more need to send light commands to each individual light of a group as Signify added support to send aggregated commands on the API.

Add support for aggregated grouped_lights commands

---

aiohue/v2/controllers/sensors.py

It was reported that our button long press workaround is no longer emitting fake long press events after the recent changes.
I can't test this myself because I do not have such a remote here but the only thing I spotted was a leftover function parameter which I removed. Also changed the code a tiny bit to make it more readable.
Beyond this there's nothing I can find to explain why the workaround code isn't working.
EDIT: issue found and fixed. Ready to merge
fixes https://github.com/home-assistant/core/issues/66819#issuecomment-1076392999

Fix and cleanup of button workaround code

---

aiohue/discovery.py

Do not crash Hue setup if Hue NUPNP server is down.
Fixes https://github.com/home-assistant/core/issues/73129

Handle Hue discovery nupnp responding bad

---

aiohue/v1/__init__.py
aiohue/v2/__init__.py

On the Hue developer website there is a message about the rate limiting status code being updated https://developers.meethue.com/rate-limiting-status-code/
Quoted below for convenience
>Dear developers,
>
> The next Hue Bridge firmware release contains a change to the HTTP status code we respond with when your client exceeds the request rate limit. Previously this would return the wrong status code 503, and going forward the correct status code will be 429.
> 
> This only applies to HTTPS connections. The 503 status code can still happen, but only if the service you try to communicate with is temporarily unavailable (i.e. server side issue), whereas 429 will happen if your application is making to many requests in a short period of time (i.e. client side issue).
>
> Hue Developer Support …

Updated rate limit statuscode

---

aiohue/v2/models/entertainment_configuration.py

"monitor" is a new configuration type for Entertainment Configurations and can be created through the latest Hue App.
Description is from the Hue API website.
Fixes #140 
Checked it by running the example vor v2 which gave the message that "monitor" was not supported, after updating the same example ran without the message

Add monitor configuration type

---

aiohue/v2/controllers/sensors.py
aiohue/v2/models/relative_rotary.py

Add support for relative_rotary resource types, to enable support for the newly launched "Hue Tap Dial"

Add support for new Hue Tap Dial (relative rotary)

---

aiohue/v2/models/feature.py

The introduction of the new Hue Festavia Christmas lights introduced a new effect in the enum: sparkle.
Fixes https://github.com/home-assistant/core/issues/82264

Add sparkle effect to fix new Festavia lights

---

aiohue/v2/controllers/base.py

To prevent ghost events we included a duplicate filter in the code (to prevent ghost events at reconnect) but this caused a side effect that rotary events also are missed if repeated. 
Fixes https://github.com/home-assistant/core/issues/78621

Fix: Missing repeated events for Philips Hue Tap Dial switch

---

aiohue/v2/controllers/scenes.py
aiohue/v2/models/resource.py
aiohue/v2/models/smart_scene.py

Signify introduced a new form of scenes "Smart Scene" which automatically transitions between various scenes during the day. This is used for the new "Natural Light" scene, which is actually not a scene but an entire new feature (resource type).
Added support for the smart scene while keeping the api backwards compatible.

Add support for smart_scene resource

---

aiohue/v1/groups.py
aiohue/v2/controllers/config.py
aiohue/v2/models/behavior_instance.py
aiohue/v2/models/behavior_script.py
aiohue/v2/models/button.py
aiohue/v2/models/device.py
aiohue/v2/models/feature.py
aiohue/v2/models/grouped_light.py
aiohue/v2/models/light.py
aiohue/v2/models/relative_rotary.py
aiohue/v2/models/resource.py
aiohue/v2/models/room.py
aiohue/v2/models/scene.py
aiohue/v2/models/smart_scene.py
aiohue/v2/models/zone.py
examples/v2_bridge.py

Signify has now officially released the definitive spec of the V2 API (and V1 is now deprecated). 
I've corrected all models so that they 100% match the official specifications.
NOTE: While working on this, I noticed some type issues by running mypy. We'll need to address that in a seperate PR and setup CI to run mypy on the v2 code.

Address changes of final V2 api release

---

aiohue/v2/models/smart_scene.py

When the Natural Light scene is in the progress of being added the active_timeslot attribute is temporary missing, account for that.

Make active_timeslot optional in smart_scene model

---

aiohue/v2/models/scene.py

This attribute is only present on recent bridge firmware versions.
To allow for a little transition period, mark it optional to prevent errors for people running older bridge versions.
Fixes #185

Mark auto_dynamic attribute optional on scene resource

---

aiohue/v2/controllers/lights.py

Full bug report in https://github.com/home-assistant/core/issues/106779. This seems like the easiest fix to me but I have no idea if this breaks anything else. Looks to me like both these values should do the same thing anyway.

Treat EffectStatus.NO_EFFECT the same as None

---

README.md
aiohue/v2/models/feature.py

When attempting to turn the dataclass back into a dict for MQTT purposes, asdict fails on SignalingFeatureStatus.  It is missing a type for the Signal.  Nearby code and classes are defined correctly.
This is a one-line change.

SignalingFeatureStatus is missing a type in the dataclass definition

---

aiohue/v2/controllers/base.py

I think this is not a proper fix as it is now dropping the event from button resources when `button` or `button.button_report` (or `relative_rotary` or `relative_rotary.rotary_report` for relative_rotary resources) are absent, while there might be other changes in the event that are relevant upstream. Since there was already code to drop the events, I expect the additional condition isn't going to hurt functionality. This should at least make the problem go away.

Patch ghost events from button and relative_rotary resources

---

aiohue/v2/controllers/sensors.py
tests/fixtures/v2_resources.json

Use `button_report.event` instead.

Remove use of deprecated `last_event` for button events

---

aiohue/v2/models/feature.py

It is returned for my lights by the Hue API:
```json
"timed_effects": {
"status_values": [
"no_effect",
"sunrise",
"sunset"
],
"status": "no_effect",
"effect_values": [
"no_effect",
"sunrise",
"sunset"
]
},
```
It is also mentioned in the documentation: https://developers.meethue.com/develop/hue-api-v2/api-reference/#resource_light_get

Add missing sunset timed effect

---

aiohue/v2/controllers/groups.py
aiohue/v2/controllers/lights.py

This method sets the brightness_delta value and its action based on the
value to up/down/stop. This can be useful if someone wants to dim a light to
the max/min value within a dedicated transition time but stop the
transition  when for instance a btn was released.
resolves https://github.com/home-assistant-libs/aiohue/issues/420

Add dimming_delta support
