aiohue/groups.py, aiohue/scenes.py
Per https://github.com/balloob/aiohue/issues/6
=> Add the "lights" property from the groups API

aiohue/config.py, aiohue/lights.py
Add `swversion` property for bridge, light.
Add `modelid` for bridge.
=> Add swversion, modelid bridge

aiohue/sensors.py
This PR cleans up the `sensors.py` file. I've removed unnecessary constructors from subclasses and added a few tabs.
=> Fix code formatting

aiohue/config.py
I would like to add a prompt to HomeAssistant (warning in log) for user to update their Philips Hue bridge if their is an update available.
=> add software update available for bridge

aiohue/bridge.py, aiohue/discovery.py, aiohue/util.py, setup.py
Make bridge aware of bridge ID.
=> Add notion of bridge ID

aiohue/bridge.py
Modification to improve error handling as per discussion on:
[https://github.com/balloob/aiohue/issues/22#issuecomment-576516183](https://github.com/balloob/aiohue/issues/22#issuecomment-576516183)
=> Improved handling of server errors

README.md, aiohue/bridge.py, aiohue/errors.py
=> Remove error wrapping

aiohue/sensors.py, example.py
=> Handle motion event

aiohue/sensors.py
=> Support remotes

aiohue/api.py, aiohue/bridge.py, aiohue/config.py, aiohue/groups.py, aiohue/lights.py, aiohue/scenes.py, aiohue/sensors.py
Map the v2 id of the button in the event to the capabilities and events of the v1 api.
=> Make sure v2 button events are translated to v1 button events

aiohue/groups.py, aiohue/sensors.py
Can be used to get a unique ID for groups.
=> Store group resource

aiohue/bridge.py, aiohue/clip.py
Convert aiohue from long polling to using event source. This will make it more reliable + it will now also resume from the last position when getting disconnected.
https://nchan.io/#eventsource
=> Use event source for streaming events

aiohue/bridge.py
=> Guard for events without a v1 id

aiohue/v2/controllers/events.py
When the eventstream connection gets lost, it reconnects.
There was however a small oversight in the reconnect logic. The reconnect was attempted within 2 seconds but without timeout on the aiohttp call so a possible deadlock. If a user has network issues/connection problems, they wil hit this deadlock if the connection is lost for more than 2 second.
This fixes the possible deadlock situation and I've added some more logging to better trace what's going on.
fixes https://github.com/home-assistant/core/issues/61819
=> Fix reconnect logic

aiohue/v2/controllers/base.py, aiohue/v2/controllers/groups.py, aiohue/v2/controllers/lights.py, aiohue/v2/controllers/scenes.py, aiohue/v2/controllers/sensors.py
Allows setting all properties and creating items from a consumer of the lib.
=> Add missing methods and properties

aiohue/v2/controllers/events.py
Do not explicitly check the client name but just set the timeout on the eventstream to 90 seconds (and send keepalive every 60 seconds)
=> Simplify keep alive, allowing multiple aiohue clients

aiohue/v1/__init__.py
This adds the retry logic we've implemented for V2 connections also in the V1 implementation
=> Add retry logic to V1 implementation

aiohue/v2/controllers/devices.py, aiohue/v2/controllers/lights.py, aiohue/v2/models/device.py, aiohue/v2/models/feature.py
This fixes the long and short flash effects as known from V1 implementation.
Related to:
https://github.com/home-assistant/core/issues/62685
Needs HA integration adjustment too
=> Fix short and long flash for lights

aiohue/v2/controllers/sensors.py
Not sure if we should do this but at least it's a temporary solution until someone at Signify fixes this.
The FOH switches are only capable of firing an event on (short) press and release, due to the battery free nature of these devices. Previously (V1 api) there was a script running on the bridge to mimic the "held down" and "long press release" events. These seem to be missing now.
As these events appear to be really missed by HA folks, I created a little workaround in our code, similar to the old script on the Hue bridge.
Reference: https://github.com/home-assistant/core/issues/61671
=> Add workaround for FOH switches

aiohue/util.py, aiohue/v2/__init__.py, aiohue/v2/controllers/base.py, aiohue/v2/controllers/config.py, aiohue/v2/controllers/devices.py, aiohue/v2/controllers/events.py, aiohue/v2/controllers/groups.py, aiohue/v2/controllers/lights.py, aiohue/v2/controllers/scenes.py, aiohue/v2/controllers/sensors.py, aiohue/v2/models/feature.py
removed annotations import as it caused an unwanted side effect
=> Fix python 3.9 compatibility

aiohue/v2/controllers/lights.py, aiohue/v2/models/feature.py, aiohue/v2/models/light.py
Allows setting the new (dynamic) effects feature on lights (e.g. from Home Assistant)
=> Add setting effect feature on light

aiohue/v2/controllers/sensors.py
I forgot a spot when adjusting the parser logic last week. Handle event now takes the (raw) dict from the event instead of the resource object. Adjusted the button workaround logic for that change.
fixes https://github.com/home-assistant/core/issues/66819
=> Fix button workaround

aiohue/v2/controllers/devices.py, aiohue/v2/controllers/groups.py
Fix some race conditions when adding/removing a light/device resulting in a (temporary) KeyError.
fixes https://github.com/home-assistant/core/issues/63591
=> Fix race condition(s) while adding/removing a light/device

aiohue/v2/controllers/lights.py
small new feature in latest firmware version
=> Add timed effects feature to light

aiohue/v2/controllers/config.py, aiohue/v2/controllers/groups.py, aiohue/v2/controllers/lights.py
Somehow forgot to update the set_state helper function to actually set the grouped light features from HA
=> Add missing parameters to the grouped_light set_state

aiohue/v2/models/feature.py
=> Fix typo in timed effects feature

aiohue/discovery.py
ignore fake Hue bridge API responses, fixes #134
=> Fix KeyError on fake Hue bridges

aiohue/util.py
=> Fix error in log when an empty dict is received for an optional value

aiohue/v2/controllers/events.py
=> Fix: KeepAlive workaround causes Geofence to malfunction

aiohue/v2/controllers/config.py, aiohue/v2/models/matter.py, aiohue/v2/models/matter_fabric.py, aiohue/v2/models/resource.py
The Hue API has been updated to provide some (basic) information about the Matter fabric it's running.
=> Add support for matter resource 

aiohue/v2/controllers/base.py, aiohue/v2/controllers/scenes.py
Add a few shortcut/utility methods to maintain API backwards compatibility within the Scenes controller
=> Add util methods for backwards compatibility in Scenes controller

aiohue/util.py, aiohue/v2/models/feature.py, tests/v2/test_parser.py
Fixes some errors in the models based on issue reports from users.
Also changed the loglevel to debug now that the API has reached stable state so we no longer spam users logs.
Fixes https://github.com/home-assistant-libs/aiohue/issues/186
Fixes https://github.com/home-assistant-libs/aiohue/issues/187
Fixes https://github.com/home-assistant/core/issues/88065
=> Fixes for some small schema parse errors

aiohue/v2/models/button.py
=> Add missing LONG_PRESS enum member for button events

aiohue/v2/models/feature.py
Small fix for backwards compatibility with old(er) bridge versions
=> Backward compatibility fix
